### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by JiXAllen** [WANGYINGYU/Occupancy-SLAM#1]
I successfully compiled it, but there was a runtime error 

./Occupancy_SLAM
Enter the names of the input files (range of scan (must), initialization poses (option, if not using odometry inputs as initialization), and odometry inputs (option, if exit), separated by spaces: ../Data/ACES/Range.txt ../Data/ACES/Pose.txt
Preprocessing, Elapsed time: 0.243509 seconds 
terminate called after throwing an instance of 'std::bad_alloc'
[1]    1235629 segmentation fault (core dumped)  ./Occupancy_SLAM

**Comment by WANGYINGYU** [comment]
> I successfully compiled it, but there was a runtime error
> 
> ./Occupancy_SLAM Enter the names of the input files (range of scan (must), initialization poses (option, if not using odometry inputs as initialization), and odometry inputs (option, if exit), separated by spaces: ../Data/ACES/Range.txt ../Data/ACES/Pose.txt Preprocessing, Elapsed time: 0.243509 seconds terminate called after throwing an instance of 'std::bad_alloc' [1] [1235629](tel:1235629) segmentation fault (core dumped) ./Occupancy_SLAM

Hi, 

Can you share your specific inputs and the configuration parameters you used.

Regards,
Yingyu

**Comment by JiXAllen** [comment]
> > I successfully compiled it, but there was a runtime error
> > ./Occupancy_SLAM Enter the names of the input files (range of scan (must), initialization poses (option, if not using odometry inputs as initialization), and odometry inputs (option, if exit), separated by spaces: ../Data/ACES/Range.txt ../Data/ACES/Pose.txt Preprocessing, Elapsed time: 0.243509 seconds terminate called after throwing an instance of 'std::bad_alloc' [1] 1235629 segmentation fault (core dumped) ./Occupancy_SLAM
> 
> Hi,
> 
> Can you share your specific inputs and the configuration parameters you used.
> 
> Regards, Yingyu
thanks for reply.
I downloaded the example datasets and use the ACES sequence.   input:`../Data/ACES/Range.txt ../Data/ACES/Pose.txt`, and use the default configs.

**Comment by WANGYINGYU** [comment]
You should modify the configuration file or use Museum b0 dataset.

Regards,
Yingyu

**Comment by JiXAllen** [comment]
> You should modify the configuration file or use Museum b0 dataset.
> 
> Regards, Yingyu

yes, it works!  Can you tell me which parameters affect whether it will run successfully？

**Comment by WANGYINGYU** [comment]
At least you should change the parameters about the laser sensor used in the special dataset, such as the angle range, etc.
